/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codecheck;

/**
 *
 * @author Usman
 */
public enum CodeCheckProps {
    // FOR SIMPLE OK/CANCEL DIALOG BOXES
    OK_PROMPT,
    CANCEL_PROMPT,
    
    // THESE ARE FOR TEXT PARTICULAR TO THE APP'S WORKSPACE CONTROLS
    
    NEXT_BUTTON,
    PREV_BUTTON,
    PLAY_BUTTON,
    HOME_BUTTON,
    RENAME_BUTTON,
    ABOUT_BUTTON,
    
    NEW_PIC,
    LOAD_PIC,
    ABOUT_PIC,
    RENAME_PIC,
    ABOUT_TOOLTIP,
    RENAME_TOOLTIP,
    
    EXTRACT_BUTTON,
    REMOVE_BUTTON,
    VIEW_BUTTON,
    REFRESH_BUTTON,
    UNZIP_BUTTON,
    EXTRACTCODE_BUTTON,
    CODECHECK_BUTTON,
    VIEWRESULTS_BUTTON,
    PROGP_LABEL,
    EXTRACT_PROGRESS,
    RENAME_PROGESS,
    UNZIP_PROGRESS,
    CODE_PROGRESS,
    
    STEP1_TABLE,
    STEP2_TABLE,
    STEP3_TABLE,
    STEP4_TABLE,
    STEP5_TABLE,
    
    STEP1_LABEL,
    STEP1_DESC_LABEL,
    STEP2_LABEL,
    STEP2_DESC_LABEL,
    STEP3_LABEL,
    STEP3_DESC_LABEL,
    STEP4_LABEL,
    STEP4_DESC_LABEL,
    STEP5_LABEL,
    STEP5_DESC_LABEL,
    PROG1_LABEL,
    PROG2_LABEL,
    PROG3_LABEL,
    PROG4_LABEL,
    PROG5_LABEL,
    LIST1_TITLE,
    LIST2_TITLE,
    LIST3_TITLE,
    LIST4_TITLE,
    LIST5_TITLE,
    JCHECK_LABEL,
    CCHECK_LABEL,
    JSCHECK_LABEL,
    CSCHECK_LABEL,
    SFT_LABEL,
    RECENT_WORK_LABEL,
    WELC_LABEL,
    CREATE_NEW_LABEL,
    NEW_TITLE,
    NEW_CONTENT,
    NEW_CONFIRMATION,
    NEW_CONF_CONTENT,
    
    CLOSE_CONFIRMATION,
    CLOSE_MESSAGE,
    XBUTTON,
    DUP_CODECHECK_TITLE,
    DUP_CODECHECK_MESSAGE,
    RENAME_TITLE,
    RENAME_MESSAGE,
    
    STEP1_VIEWT,
    STEP1_VIEWM,
    ABOUT_TITLE,
    ABOUT_MESSAGE,
    // FOR OTHER INTERACTIONS
    APP_PATH_WORK,
    INVALID_IMAGE_PATH_TITLE,
    INVALID_IMAGE_PATH_MESSAGE,
    FILENAME_NULL_MESSAGE,
    FILENAME_NULL_TITLE,
}
